#!/bin/bash

set -euo pipefail

docker build -t amazon_integration -f Dockerfile .
docker tag -f amazon_integration:latest 914794084459.dkr.ecr.us-east-1.amazonaws.com/amazon_integration:latest
docker push 914794084459.dkr.ecr.us-east-1.amazonaws.com/amazon_integration:latest
